[package]
name = "wasm-lib"
version = "0.1.0"
edition = "2021"
description = "Web Wordle solver Wasm library"
repository = "https://github.com/tropicbliss/wordlesolver"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
phf = { version = "0.10.1", features = ["macros"] }
serde = { version = "1.0.137", features = ["derive"] }
wasm-bindgen = { version = "0.2.80", features = ["serde-serialize"] }
wee_alloc = { version = "0.4.5", optional = true }

[build-dependencies]
phf_codegen = "0.10.0"

[profile.release]
opt-level = "s"
